<?php

namespace Blabs\FidelyNet\Constants;

final class CardMovementConstants
{
    const KIND_IDS_MAP = [
        1  => 'Nuova Card',
        2  => 'Spesa',
        3  => 'Carico Punti',
        4  => 'Carico Crediti',
        5  => 'Beneficio Diretto',
        6  => 'Estensione Data Scadenza',
        7  => 'Richiesta Premio',
        9  => 'Commissione Estensione',
        10 => 'Svalutazione Punti',
        11 => 'Commissioni MLM',
        12 => 'Trasferimento Punti',
        13 => 'Eliminazione Movimento',
        14 => 'Nuova Gift Card',
        15 => 'Scarico Punti',
        16 => 'Ritiro Premio',
        17 => 'Scarico Crediti',
        18 => 'Scarico Crediti Gift Card',
        19 => 'Blocco Card',
        20 => 'Sblocco Card',
        21 => 'Sostituzione Card',
        22 => 'Assegnazione Card',
        23 => 'Attivazione Card',
        24 => 'Carico Punti per Completamento Dati',
        25 => 'Modifica Password Cliente',
        26 => 'Cambio Categoria',
        27 => 'Restituzione Spesa',
        28 => 'Commissione Carico MLM',
        29 => 'Commissione Scarico MLM',
        30 => 'Blocco Area Cliente',
        31 => 'Sblocco Area Cliente',
        32 => 'Check In Cliente',
        33 => 'Check Out Cliente',
        34 => 'Eliminazione Cliente',
        35 => 'Interazione Social',
        36 => 'Completamento Sondaggio',
        37 => 'Sottoscrizione',
        38 => 'Registrazione su invito di un amico',
        39 => 'Invito ad un amico',
        40 => 'Storno di una vendita',
        41 => 'Prenotazione/pagamento merce',
        42 => 'Storno vendita merce',
        43 => 'Pagamento merce dealer',
        44 => 'Trasferimento crediti',
        45 => 'Gamification',
        46 => 'Cashback',
        47 => 'Blocco del cliente al riscatto punti',
        48 => 'Sblocco del cliente al riscatto punti',
        49 => 'Richiesta Gift Card',
        50 => 'Richiesta trasferimenti esterni',
        51 => 'Ritiro Gift Card',
        52 => 'Attivazione cliente',
        53 => 'Invio sondaggio',
        54 => 'Ritiro trasferimento esterno',
        55 => 'Restituzione premi',
        56 => 'Badge ottenuto',
        57 => 'Modifica dati personali',
        58 => 'Cambio livello del cliente',
        59 => 'Carico punti status',
    ];
}
